# Generated by Django 5.1.6 on 2025-02-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServerUpdateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_update_time",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("server_update_status", models.BooleanField(default=False)),
                (
                    "server_update_error",
                    models.TextField(blank=True, default="", null=True),
                ),
            ],
            options={
                "verbose_name": "Server Update",
                "verbose_name_plural": "Server Updates",
                "db_table": "server_update",
                "ordering": ["-server_update_time"],
            },
        ),
    ]
