# Generated by Django 5.1.6 on 2025-02-15 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_itemclickmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkmodel",
            name="not_working_count",
        ),
        migrations.RemoveField(
            model_name="linkmodel",
            name="working_count",
        ),
        migrations.CreateModel(
            name="LinkActionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("not_working", "Not Working"),
                        ],
                        max_length=255,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.linkmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Link Action",
                "verbose_name_plural": "Link Actions",
            },
        ),
    ]
