# Generated by Django 5.1.6 on 2025-02-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_linkmodel_not_working_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkactionmodel",
            name="action",
            field=models.CharField(
                choices=[
                    ("working", "Working"),
                    ("not_working", "Not Working"),
                    ("spam", "Spam"),
                ],
                max_length=255,
            ),
        ),
    ]
